install script updated

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,253 +1,222 @@
 #!/bin/bash
 
+# Set colors for better readability
 CRE=$(tput setaf 1)
 CYE=$(tput setaf 3)
 CGR=$(tput setaf 2)
 CBL=$(tput setaf 4)
 BLD=$(tput bold)
 CNC=$(tput sgr0)
- 
-backup_folder=~/.RiceBackup
-date=$(date +%Y%m%d-%H%M%S)
 
-logo() {
+# Define backup folder and date
+backup_folder="$HOME/.RiceBackup/$(date +%Y%m%d_%H%M%S)"
 
-	local text="${1:?}"
-	echo -en "                                 
-  	dotfiles\n\n"
-	printf ' %s [%s%s %s%s %s]%s\n\n' "${CRE}" "${CNC}" "${CYE}" "${text}"
+# Function for displaying a logo or header
+print_logo() {
+    local text="${1:?}"
+    printf ' %s [%s%s %s%s %s]%s\n\n' "${CRE}" "${CNC}" "${CYE}" "${text}" "${CNC}" "${CRE}" "${CNC}"
 }
 
-# Check if this script is run as root
-if [ "$(id -u)" = 0 ]; then
-	echo "This script MUST NOT be run as root."
-	exit 1
-fi
+# Function to check if a package is installed
+is_installed() {
+    pacman -Qi "$1" &>/dev/null
+    return $?
+}
 
-# Intro
-clear
-logo "Welcome!"
-printf '%s%sThis script will automatically install fully-featured tiling/floating window manager-based system on any Arch Linux or Arch-based system. \n\nMy dotfiles DO NOT modify any of your system configuration. \nYou will be prompted for your root password to install missing dependencies \n\nThis script doesnt have potential power to break your system, it only copies files from my repo to your HOME directory. %s\n\n' "${BLD}" "${CRE}" "${CNC}"
+# Function for backing up files
+perform_backup() {
+    local source_path="$1"
+    local target_path="$2"
+    local folder_name="$(basename "$source_path")"
+    
+    if [ -d "$source_path" ]; then
+        mv "$source_path" "$target_path"
+        echo "$folder_name folder backed up successfully at $target_path"
+    else
+        echo "The folder $folder_name does not exist at $source_path"
+    fi
+}
 
-while true; do
-	read -rp " Do you want to continue? [y/n]: " yn
-	case $yn in
-	[Yy]*) break ;;
-	[Nn]*) exit ;;
-	*) printf "Just write 'y' or 'n'\n\n" ;;
-	esac
-done
+# Function for installing plugins
+install_plugin() {
+    local repo=$1
+    local target_dir=${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/$(basename "$repo")
+    
+    if [ -d "$target_dir" ]; then
+        printf "%s already installed. Skipping.\n" "$(basename "$repo")"
+    else
+        printf "Installing %s...\n" "$(basename "$repo")"
+        git clone "$repo" "$target_dir"
+    fi
+}
+
+# Main script
 clear
+print_logo "Welcome!"
 
 # Update system
-logo "Updating system"
+print_logo "Updating system"
 sudo rm -rf /var/lib/pacman/db.lck
 sudo pacman -Syu --noconfirm
-printf "%s%sDone!!%s\n\n" "${BLD}" "${CGR}" "${CNC}"
-sleep 2
-clear
 
 # Install X.Org
-logo "Installing X.Org"
+print_logo "Installing X.Org"
 sudo pacman -S --needed --noconfirm xorg xorg-drivers
-printf "%s%sDone!!%s\n\n" "${BLD}" "${CGR}" "${CNC}"
-sleep 2
-clear
 
 # Install Pipewire (audio)
-logo "Installing Pipewire (audio)"
+print_logo "Installing Pipewire (audio)"
 yes y | sudo pacman -S --needed pipewire pipewire-pulse wireplumber
-printf "%s%sDone!!%s\n\n" "${BLD}" "${CGR}" "${CNC}"
-sleep 2
-clear
 
 # Install Yay (AUR helper)
-logo "Installing yay"
+print_logo "Installing yay"
 if command -v yay &>/dev/null; then
-	echo "Yay is installed in your system"
+    echo "Yay is installed on your system"
 else
-	sudo pacman -S --needed --noconfirm base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si --noconfirm && cd ..
+    sudo pacman -S --needed --noconfirm base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si --noconfirm && cd ..
 fi
-sleep 2
-clear
 
 # Install packages
-logo "Installing needed packages"
-
+print_logo "Installing needed packages"
 dependencies=(kitty zsh bspwm ly cerebro-bin pywal-git dragon-drop ibus-daemon bibata-cursor-theme polkit-gnome dunst feh git gtk-engine-murrine gvfs gvfs-afc gvfs-mtp gvfs-smb htop librewolf lmaofetch lxappearance mpc mpd mpv ncmpcpp neovim networkmanager pamixer pavucontrol qogir-icon-theme ranger rofi scrot sed sxhkd udisks2 ttf-roboto-mono ttf-roboto-mono-nerd unzip xclip xdg-user-dirs-gtk xorg-xinit zathura zathura-pdf-mupdf zip picom-simpleanims-next-git vscodium-bin )
 
-is_installed() {
-	pacman -Qi "$1" &>/dev/null
-	return $?
-}
-
 printf "%s%sChecking for required packages%s\n" "${BLD}" "${CBL}" "${CNC}"
-for paquete in "${dependencies[@]}"; do
-	if ! is_installed "$paquete"; then
-		yay -S --noconfirm "$paquete"
-		printf "\n"
-	else
-		printf '%s%s is already installed on your system!%s\n' "${CGR}" "$paquete" "${CNC}"
-	fi
+for package in "${dependencies[@]}"; do
+    if ! is_installed "$package"; then
+        yay -S --noconfirm "$package"
+        printf "\n"
+    else
+        printf '%s%s is already installed on your system!%s\n' "${CGR}" "$package" "${CNC}"
+    fi
 done
-sleep 2
-clear
 
 # Preparing folders
-logo "Preparing Folders"
-if [ ! -e $HOME/.config/user-dirs.dirs ]; then
-	xdg-user-dirs-update
-	echo "Creating xdg-user-dirs"
+print_logo "Preparing Folders"
+if [ ! -e "$HOME"/.config/user-dirs.dirs ]; then
+    xdg-user-dirs-update
+    echo "Creating xdg-user-dirs"
 else
-	echo "user-dirs.dirs already exists"
+    echo "user-dirs.dirs already exists"
 fi
-sleep 2
+
+# Backup dotfiles
+print_logo "Backing-up dotfiles"
+printf "Backup files will be stored in %s%s%s/.RiceBackup%s \n\n" "${BLD}" "${CRE}" "$HOME" "${CNC}"
+sleep 1
+mkdir -p "$backup_folder"
+
+# Backup specified config folders
+for folder in kitty bspwm btop gtk-2.0 gtk-3.0 gtk-4.0 mpd ncmpcpp neovim ranger qBittorrent zathura; do
+    perform_backup "$HOME/.config/$folder" "$backup_folder/${folder}_$(date +%Y%m%d_%H%M%S)"
+done
+
+# Backup wallpapers folder
+perform_backup "$HOME/Pictures/wallpapers" "$backup_folder/wallpapers_$(date +%Y%m%d_%H%M%S)"
+
+# Backup specific files
+[ -f "$HOME/.zshrc" ] && mv "$HOME/.zshrc" "$backup_folder/.zshrc-backup-$(date +%Y%m%d-%H%M%S)"
+[ -f "$HOME/.fehbg" ] && mv "$HOME/.fehbg" "$backup_folder/.fehbg-backup-$(date +%Y%m%d-%H%M%S)"
+clear 
+
+# Configure Zsh and install plugins
+print_logo "Configuring Zsh.."
+printf "Installing ohmyzsh..\n"
+sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
+install_plugin https://github.com/zsh-users/zsh-autosuggestions
+install_plugin https://github.com/zsh-users/zsh-syntax-highlighting.git
+install_plugin https://github.com/zsh-users/zsh-history-substring-search
+install_plugin https://github.com/MichaelAquilina/zsh-autoswitch-virtualenv.git
+install_plugin https://github.com/MichaelAquilina/zsh-you-should-use.git
+install_plugin https://github.com/MichaelAquilina/zsh-auto-notify.git
+printf "Installing prompt (Starship)...\n"
+curl -fsSL https://starship.rs/install.sh | bash
+clear
+
+# Install wallpapers
+print_logo "Install wallpapers"
+git clone https://github.com/whoisYoges/wallpapers.git "$HOME"/wallpapers || { echo "Error: Unable to clone wallpapers repository"; sleep 2 && exit 1; }
+mkdir -p "$HOME"/Pictures/wallpapers
+mv "$HOME"/wallpapers/* "$HOME"/Pictures/wallpapers || { echo "Error: Unable to move wallpapers"; sleep 2 && exit 1;}
+rm -rf "$HOME"/wallpapers
+echo "Wallpapers installed successfully."
 clear
 
 # Downloading dotfiles
-logo "Downloading dotfiles"
+print_logo "Downloading dotfiles"
 [ -d ~/dotfiles ] && rm -rf ~/dotfiles
 printf "Cloning rice\n"
-cd "$HOME"
+cd "$HOME" || exit
 git clone --depth=1 https://github.com/MineNique/plane-dotfiles.git
-printf "%s%sDone!!%s\n\n" "${BLD}" "${CGR}" "${CNC}"
-sleep 2
 clear
-
-# Backup dotfiles
-logo "Backing-up dotfiles"
-printf "Backup files will be stored in %s%s%s/.RiceBackup%s \n\n" "${BLD}" "${CRE}" "$HOME" "${CNC}"
-sleep 1
-
-if [ ! -d "$backup_folder" ]; then
-	mkdir -p "$backup_folder"
-fi
-
-for folder in kitty bspwm btop gtk-2.0 gtk-3.0 gtk-4.0 mpd ncmpcpp neovim ranger style style_folder zathura; do
-	if [ -d "$HOME/.config/$folder" ]; then
-		mv "$HOME/.config/$folder" "$backup_folder/${folder}_$date"
-		echo "$folder folder backed up successfully at $backup_folder/${folder}_$date"
-	else
-		echo "The folder $folder does not exist in $HOME/.config/"
-	fi
-done
-
-for folder in wallpapers; do
-	if [ -d "$HOME"/Pictures/$folder ]; then
-		mv "$HOME"/Pictures/$folder "$backup_folder"/${folder}_$date
-		echo "$folder folder backed up successfully at $backup_folder/${folder}_$date"
-	else
-		echo "The folder $folder does not exist in $HOME"
-	fi
-done
-
-
-[ -f ~/.zshrc ] && mv ~/.zshrc ~/.RiceBackup/.zshrc-backup-"$(date +%Y.%m.%d-%H.%M.%S)"
-[ -f ~/.fehbg ] && mv ~/.fehbg ~/.RiceBackup/.fehbg-backup-"$(date +%Y.%m.%d-%H.%M.%S)"
-printf "%s%sDone!!%s\n\n" "${BLD}" "${CGR}" "${CNC}"
-sleep 2
-clear
-
-
-# Install Zsh
-logo "Configuring Zsh.."
-printf "Installing ohmyzsh..\n"
-
-sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
-
-printf "Installing zsh-autosuggestions..\n"
-git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
-
-printf "Installing zsh-syntax-highlighting..\n"
-git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
-
-printf "Installing zsh-history-substring-search..\n"
- git clone https://github.com/zsh-users/zsh-history-substring-search ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-history-substring-search
-
-printf "Installing autoswitch_virtualenv..\n"
-git clone https://github.com/MichaelAquilina/zsh-autoswitch-virtualenv.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/autoswitch_virtualenv
-
-printf "Installing you-should-use..\n"
-git clone https://github.com/MichaelAquilina/zsh-you-should-use.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/you-should-use
-
-printf "Installing auto-notify..\n"
-git clone https://github.com/MichaelAquilina/zsh-auto-notify.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/auto-notify
-
-printf "Installing prompt..\n"
-curl -sS https://starship.rs/install.sh | sh
-
-# Install wallpapers
-logo "Cloning wallpapers.."
-git clone https://github.com/whoisYoges/lwalpapers.git "$HOME"/lwalpapers
-mkdir "$HOME"/Pictures/walpapers
-mv "$HOME"/lwalpapers/walpapers/* "$HOME"/Pictures/walpapers
-rm -rf "$HOME"/lwalpapers
 
 # Installing dotfiles
-logo "Installing dotfiles.."
+print_logo "Installing dotfiles.."
 printf "Copying files to respective directories..\n"
 
-[ ! -d ~/.config ] && mkdir -p "$HOME"/.config
-[ ! -d ~/.fonts ] && mkdir -p "$HOME"/.fonts
-[ ! -d ~/.local/share/applications ] && mkdir -p "$HOME"/.local/share/applications
+# Create necessary directories if they don't exist
+[ ! -d "$HOME"/.config ] && mkdir -p "$HOME"/.config
+[ ! -d "$HOME"/.fonts ] && mkdir -p "$HOME"/.fonts
+[ ! -d "$HOME"/.local/share/applications ] && mkdir -p "$HOME"/.local/share/applications
 
-for archivos in "$HOME"/dotfiles/config/*; do
-	cp -r "${archivos}" "$HOME"/.config/
-	if [ $? -eq 0 ]; then
-		printf "%s%s%s folder copied successfully!%s\n" "${BLD}" "${CGR}" "${archivos}" "${CNC}"
-	else
-		printf "%s%s%s failed to been copied, you must copy it manually%s\n" "${BLD}" "${CRE}" "${archivos}" "${CNC}"
-		sleep 1
-	fi
+# Copy configuration files to ~/.config
+for file in "$HOME"/dotfiles/config/*; do
+    cp -r "$file" "$HOME"/.config/
+    if [ $? -eq 0 ]; then
+        printf "%s%s%s folder copied successfully!%s\n" "${BLD}" "${CGR}" "$file" "${CNC}"
+    else
+        printf "%s%s%s failed to be copied, you must copy it manually%s\n" "${BLD}" "${CRE}" "$file" "${CNC}"
+        sleep 1
+    fi
 done
 
-for archivos in "$HOME"/dotfiles/home/*; do
-	cp -r "${archivos}" "$HOME"/
-	if [ $? -eq 0 ]; then
-		printf "%s%s%s folder copied successfully!%s\n" "${BLD}" "${CGR}" "${archivos}" "${CNC}"
-	else
-		printf "%s%s%s failed to been copied, you must copy it manually%s\n" "${BLD}" "${CRE}" "${archivos}" "${CNC}"
-		sleep 1
-	fi
+# Copy home directory files to ~/
+for file in "$HOME"/dotfiles/home/*; do
+    cp -r "$file" "$HOME"/
+    if [ $? -eq 0 ]; then
+        printf "%s%s%s folder copied successfully!%s\n" "${BLD}" "${CGR}" "$file" "${CNC}"
+    else
+        printf "%s%s%s failed to be copied, you must copy it manually%s\n" "${BLD}" "${CRE}" "$file" "${CNC}"
+        sleep 1
+    fi
 done
 
-for archivos in "$HOME"/dotfiles/themes/*; do
-	sudo cp -r "${archivos}" /usr/share/themes/
-	if [ $? -eq 0 ]; then
-		printf "%s%s%s folder copied successfully!%s\n" "${BLD}" "${CGR}" "${archivos}" "${CNC}"
-	else
-		printf "%s%s%s failed to been copied, you must copy it manually%s\n" "${BLD}" "${CRE}" "${archivos}" "${CNC}"
-		sleep 1
-	fi
+# Copy theme files to /usr/share/themes/
+for file in "$HOME"/dotfiles/themes/*; do
+    sudo cp -r "$file" /usr/share/themes/
+    if [ $? -eq 0 ]; then
+        printf "%s%s%s folder copied successfully!%s\n" "${BLD}" "${CGR}" "$file" "${CNC}"
+    else
+        printf "%s%s%s failed to be copied, you must copy it manually%s\n" "${BLD}" "${CRE}" "$file" "${CNC}"
+        sleep 1
+    fi
 done
 
-printf "%s%sDone!\n\n" "${BLD}" "${CGR}" "${CNC}"
+printf "%s%sDone!\n\n" "${BLD}" "${CGR}"
 sleep 2
 clear
 
-# Configuring dotfiles
-logo "Configuring dotfiles"
+# Configure dotfiles
+print_logo "Configuring dotfiles"
 chmod -R +x ~/.config/
-chmod +x ~/.xinitrc
-[ -d ~/.ssh ] && chmod  0700 ~/.ssh
-[ -d ~/.gnupg ] && chmod  0700 ~/.gnupg
-mkdir ~/.cache/zsh
+[ -d ~/.xinitrc ] && chmod +x ~/.xinitrc
+[ -d ~/.ssh ] && chmod 0700 ~/.ssh
+[ -d ~/.gnupg ] && chmod 0700 ~/.gnupg
+mkdir -p ~/.cache/zsh
 touch ~/.cache/zsh/zhistory 
 [ -d ~/.cache/zsh/zhistory ] && chmod 0600 ~/.cache/zsh/zhistory
-printf "%s%sDone!\n\n" "${BLD}" "${CGR}" "${CNC}"
+printf "%s%sDone!\n\n" "${BLD}" "${CGR}"
 sleep 2
 clear
 
-# Configuring pacman (for what???)
-logo "Configuring pacman (for what???)"
+# Configure pacman
+print_logo "Configuring pacman"
 grep "^Color" /etc/pacman.conf >/dev/null || sudo sed -i "s/^#Color$/Color/" /etc/pacman.conf
 grep "ILoveCandy" /etc/pacman.conf >/dev/null || sudo sed -i "/#VerbosePkgLists/a ILoveCandy" /etc/pacman.conf
-printf "%s%sDone!\n\n" "${BLD}" "${CGR}" "${CNC}"
+printf "%s%sDone!\n\n" "${BLD}" "${CGR}"
 sleep 2
 clear
 
-# Enabling services
-logo "Enabling services"
+# Enable services
+print_logo "Enabling services"
 systemctl --user enable mpd.service
 systemctl --user start mpd.service
 sudo systemctl enable NetworkManager
@@ -257,14 +226,14 @@ printf "%s%sDone!%s\n\n" "${BLD}" "${CGR}" "${CNC}"
 sleep 2
 clear
 
-# Restart
-logo "Done!"
+# Final message and restart prompt
+print_logo "Done!"
 printf "%s%sThanks for using my config! %s\n" "${BLD}" "${CYE}" "${CNC}"
 while true; do
-	read -rp "Do you want to restart now? [y/n]: " yn
-	case $yn in
-	[Yy]*) reboot ;;
-	[Nn]*) exit ;;
-	*) printf "Just write 'y' or 'n'\n\n" ;;
-	esac
+    read -rp "Do you want to restart now? [y/n]: " yn
+    case $yn in
+        [Yy]*) reboot ;;
+        [Nn]*) exit ;;
+        *) printf "Just write 'y' or 'n'\n\n" ;;
+    esac
 done
